name: Java CI using Maven
on:
 push:
 branches:
 - main
 pull_request:
 branches:
 - main
jobs:
 build:
 runs-on: ubuntu-latest
 steps:
 - name: Checkout Repository
 uses: actions/checkout@v4
 - name: Set up Java
 uses: actions/setup-java@v4
 with:
 distribution: temurin
 java-version: '17'
 - name: Cache Maven Packages
 uses: actions/cache@v4
 with:
 path: ~/.m2
 key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
 - name: Build Project
 run: mvn clean install
